# .github/workflows/frontend.yml
name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.5

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test-ci

      - name: Check for "deploy" in commit message
        id: deploy_check
        run: |
          if [[ $(git log -1 --pretty=%s) == *"deploy"* ]]; then
            echo "::set-output name=should_deploy::true"
          else
            echo "::set-output name=should_deploy::false"
          fi

      - name: Deploy App
        if: steps.deploy_check.outputs.should_deploy == 'true'
        run:  curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }} 
